spec:
  extProc:
    allowModeOverride: false
    failureModeAllow: true
    filterStage:
      stage: "AuthZStage"
    grpcService:
      extProcServerRef:
        name: "moesif-extproc-plugin"
        namespace: "gloo-system"
    processingMode:
      requestHeaderMode: "SEND"
      responseHeaderMode: "SEND"
